"""add meeting file fields

Revision ID: f23e0e2e3bfd
Revises: 1ca7055d36d7
Create Date: 2026-08-14 05:36:10.128361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23e0e2e3bfd'
down_revision: Union[str, Sequence[str], None] = '1ca7055d36d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('file_name', sa.String(), nullable=True))
    op.add_column('meetings', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'file_path')
    op.drop_column('meetings', 'file_name')
    # ### end Alembic commands ###
